import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("po", "routes/po._index.tsx"),
  route("po/:id/pdf", "routes/po.$id.pdf.tsx"),
  route("receiving", "routes/receiving._index.tsx"),
  route("inventory", "routes/inventory.tsx"),
  route("skus", "routes/skus._index.tsx"),
  route("skus/new", "routes/skus.new.tsx"),
  route("skus/print", "routes/skus.print.tsx"),
  route("skus/:id", "routes/skus.$id.tsx"),
  route("build", "routes/build.tsx"),
  route("work-orders", "routes/work-orders._index.tsx"),
  route("transfers", "routes/transfers._index.tsx"),
  route("time-clock", "routes/time-clock.tsx"),
  route("worker-dashboard", "routes/worker-dashboard.tsx"),
  route("clock-out-entry", "routes/clock-out-entry.tsx"),
  route("my-efficiency", "routes/my-efficiency.tsx"),
  route("task-assignments", "routes/task-assignments.tsx"),
  route("time-entry-approvals", "routes/time-entry-approvals.tsx"),
  route("users", "routes/users.tsx"),
  route("schedules", "routes/schedules.tsx"),
  route("capacity", "routes/capacity.tsx"),
  route("audit-log", "routes/audit-log.tsx"),
  route("notifications", "routes/notifications.tsx"),
] satisfies RouteConfig;
