import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("po", "routes/po._index.tsx"),
  route("po/:id/pdf", "routes/po.$id.pdf.tsx"),
  route("receiving", "routes/receiving._index.tsx"),
  route("inventory", "routes/inventory.tsx"),
  route("skus", "routes/skus._index.tsx"),
  route("skus/new", "routes/skus.new.tsx"),
  route("skus/import", "routes/skus.import.tsx"),
  route("skus/export", "routes/skus.export.tsx"),
  route("skus/print", "routes/skus.print.tsx"),
  route("skus/:id", "routes/skus.$id.tsx"),
  route("build", "routes/build.tsx"),
  route("transfers", "routes/transfers._index.tsx"),
  route("time-clock", "routes/time-clock.tsx"),
  route("time-off-request", "routes/time-off-request.tsx"),
  route("worker-dashboard", "routes/worker-dashboard.tsx"),
  route("worker-task-view", "routes/worker-task-view.tsx"),
  route("worker-submit-task", "routes/worker-submit-task.tsx"),
  route("worker-clock-out-confirm", "routes/worker-clock-out-confirm.tsx"),
  route("worker-work-summary", "routes/worker-work-summary.tsx"),
  route("my-rejected-tasks", "routes/my-rejected-tasks.tsx"),
  route("clock-out-entry", "routes/clock-out-entry.tsx"),
  route("my-efficiency", "routes/my-efficiency.tsx"),
  route("worker-efficiency", "routes/worker-efficiency.tsx"),
  route("task-assignments", "routes/task-assignments.tsx"),
  route("time-entry-approvals", "routes/time-entry-approvals.tsx"),
  route("users", "routes/users.tsx"),
  route("schedules", "routes/schedules.tsx"),
  route("payroll", "routes/payroll.tsx"),
  route("capacity", "routes/capacity.tsx"),
  route("forecasting", "routes/forecasting.tsx"),
  route("quality-control", "routes/quality-control.tsx"),
  route("disposals", "routes/disposals.tsx"),
  route("admin-submit-worker-task", "routes/admin-submit-worker-task.tsx"),
  route("admin-manual-time-entry", "routes/admin-manual-time-entry.tsx"),
  route("process-tutorials", "routes/process-tutorials.tsx"),
  route("tutorials", "routes/tutorials.tsx"),
  route("audit-log", "routes/audit-log.tsx"),
  route("notifications", "routes/notifications.tsx"),
  route("api/upload-image", "routes/api.upload-image.tsx"),
  route("api/test-cloudinary", "routes/api.test-cloudinary.tsx"),
] satisfies RouteConfig;
